### ISSUE TITLE
Churrasco do PPGE

### ISSUE THREAD

**Issue by PPSF** [pcjunger/studyGroup#1]
[Evento teste]

Olá pessoal!

Aproveito a criação do grupo de estudos para lembrá-los que o churrasco desse ano ainda não aconteceu. Vamos?

Abraços a todos!

**Comment by vjgiglio** [comment]
Simbora!! Levo as frutas e legumes. 

Abraços

**Comment by yosaralu** [comment]
Onde e quando que seria o churrasco? 😀

Sara Lucía Colmenares-T.

_PhD student at Ecology DepartmentUniversidade Federal do Rio de Janeiro,
UFRJ._

---

_Weight"All in all in, all in a dayA day it changes everything""Remember to
look up at the stars and not down at your feet.Try to make sense of what
you see,and wonder about what makes the universe exist" S.H._

**Comment by pcjunger** [comment]
Pessoal, a postagem valeu como um primeiro teste, mas vamos tentar usar esse grupo para discutir coisas relacionadas ao R, Git, estatística etc. Vou fechar esse issue aqui, ok? Podemos discutir o churrasco de outra forma :-)
