### ISSUE TITLE
Website link

### ISSUE THREAD

**Issue by adletaw** [pcjunger/studyGroup#2]
Hi @pcjunger !  You can link to the website version of your study group by clicking "Edit" at the top of your repository.  It allows you to add a description of the group, and a link to the website.

Boa sorte todo mundo! :smile:

**Comment by pcjunger** [comment]
Hi @adletaw ! It sounds like a good idea. Thanks for sharing!

**Comment by pcjunger** [comment]
Done! Have a go everyone!

**Comment by adletaw** [comment]
Awesome!!!!!!!! :grinning: :+1:
